// A3TI
force A3TI_ACE_JAVELIN = false;
force A3TI_ALLOW_TANK_DRIVER = false;
force A3TI_ALLOW_VANILLA_TI = true;
force A3TI_ENABLE_ZEUS = true;
force A3TI_HD_VISION_FIGHTER = false;
force A3TI_HD_VISION_LANDVEH = true;
force A3TI_HD_VISION_SHIP = false;
force A3TI_HD_VISION_UAV = true;
force A3TI_REMOVE_FILMGRAIN_RHS = true;

// ACE Abschüsse
force ace_killtracker_showCrewKills = false;
force ace_killtracker_trackAI = true;

// ACE Allgemein
force ace_common_allowFadeMusic = true;
force ace_common_checkExtensions = false;
force ace_common_checkPBOsAction = 0;
force ace_common_checkPBOsCheckAll = false;
force ace_common_checkPBOsWhitelist = "[]";
force ace_common_deployedSwayFactor = 1;
ace_common_displayTextColor = [0,0,0,0.1];
ace_common_displayTextFontColor = [1,1,1,1];
force ace_common_enableSway = false;
ace_common_epilepsyFriendlyMode = false;
force ace_common_magneticDeclination = false;
ace_common_progressBarInfo = 2;
force ace_common_restedSwayFactor = 1;
ace_common_settingFeedbackIcons = 1;
ace_common_settingProgressBarLocation = 0;
force ace_common_swayFactor = 1;

// ACE Artillerie
force ace_artillerytables_advancedCorrections = false;
force ace_artillerytables_disableArtilleryComputer = false;
force ace_mk6mortar_airResistanceEnabled = false;
force ace_mk6mortar_allowCompass = true;
force ace_mk6mortar_allowComputerRangefinder = true;
force ace_mk6mortar_useAmmoHandling = false;

// ACE Außenlaststationen
force ace_pylons_enabledForZeus = true;
force ace_pylons_enabledFromAmmoTrucks = true;
force ace_pylons_rearmNewPylons = false;
force ace_pylons_requireEngineer = false;
force ace_pylons_requireToolkit = true;
force ace_pylons_searchDistance = 15;
force ace_pylons_timePerPylon = 5;

// ACE Benutzeroberfläche
force ace_ui_allowSelectiveUI = true;
ace_ui_ammoCount = false;
ace_ui_ammoType = true;
ace_ui_commandMenu = true;
force ace_ui_enableSpeedIndicator = true;
ace_ui_firingMode = true;
ace_ui_groupBar = false;
ace_ui_gunnerAmmoCount = true;
ace_ui_gunnerAmmoType = true;
ace_ui_gunnerFiringMode = true;
ace_ui_gunnerLaunchableCount = true;
ace_ui_gunnerLaunchableName = true;
ace_ui_gunnerMagCount = true;
ace_ui_gunnerWeaponLowerInfoBackground = true;
ace_ui_gunnerWeaponName = true;
ace_ui_gunnerWeaponNameBackground = true;
ace_ui_gunnerZeroing = true;
ace_ui_hideDefaultActionIcon = false;
ace_ui_magCount = true;
ace_ui_soldierVehicleWeaponInfo = true;
ace_ui_staminaBar = true;
ace_ui_stance = true;
ace_ui_throwableCount = true;
ace_ui_throwableName = true;
ace_ui_vehicleAltitude = true;
ace_ui_vehicleCompass = true;
ace_ui_vehicleDamage = true;
ace_ui_vehicleFuelBar = true;
ace_ui_vehicleInfoBackground = true;
ace_ui_vehicleName = true;
ace_ui_vehicleNameBackground = true;
ace_ui_vehicleRadar = true;
ace_ui_vehicleSpeed = true;
ace_ui_weaponLowerInfoBackground = true;
ace_ui_weaponName = true;
ace_ui_weaponNameBackground = true;
ace_ui_zeroing = true;

// ACE Crew Served Weapons
force ace_csw_ammoHandling = 1;
force ace_csw_defaultAssemblyMode = true;
ace_csw_dragAfterDeploy = false;
force ace_csw_handleExtraMagazines = true;
force ace_csw_handleExtraMagazinesType = 0;
force ace_csw_progressBarTimeCoefficent = 1;

// ACE Durchzündung
force ace_cookoff_ammoCookoffDuration = 1;
force ace_cookoff_cookoffDuration = 1;
force ace_cookoff_destroyVehicleAfterCookoff = false;
force ace_cookoff_enableAmmobox = true;
force ace_cookoff_enableAmmoCookoff = true;
force ace_cookoff_enableFire = true;
force ace_cookoff_probabilityCoef = 1;
force ace_cookoff_removeAmmoDuringCookoff = true;

// ACE Einheitenwechsel
force ace_switchunits_enableSafeZone = true;
force ace_switchunits_enableSwitchUnits = false;
force ace_switchunits_safeZoneRadius = 100;
force ace_switchunits_switchToCivilian = false;
force ace_switchunits_switchToEast = false;
force ace_switchunits_switchToIndependent = false;
force ace_switchunits_switchToWest = false;

// ACE Erweiterte Ausdauer
force ace_advanced_fatigue_enabled = true;
force ace_advanced_fatigue_enableStaminaBar = true;
force ace_advanced_fatigue_fadeStaminaBar = true;
force ace_advanced_fatigue_loadFactor = 1.49937;
force ace_advanced_fatigue_performanceFactor = 1;
force ace_advanced_fatigue_recoveryFactor = 1;
force ace_advanced_fatigue_terrainGradientFactor = 1.49937;

// ACE Erweiterte Ballistik
force ace_advanced_ballistics_ammoTemperatureEnabled = true;
force ace_advanced_ballistics_barrelLengthInfluenceEnabled = true;
force ace_advanced_ballistics_bulletTraceEnabled = true;
force ace_advanced_ballistics_enabled = false;
force ace_advanced_ballistics_muzzleVelocityVariationEnabled = true;
force ace_advanced_ballistics_simulationInterval = 0.05;

// ACE Erweiterter Fahrzeugsschaden
force ace_vehicle_damage_enableCarDamage = true;
force ace_vehicle_damage_enabled = true;

// ACE Erweitertes Wurfsystem
ace_advanced_throwing_enabled = true;
force ace_advanced_throwing_enablePickUp = true;
force ace_advanced_throwing_enablePickUpAttached = true;
ace_advanced_throwing_enableTempWindInfo = true;
ace_advanced_throwing_showMouseControls = true;
ace_advanced_throwing_showThrowArc = true;

// ACE Fahrzeuge
force ace_novehicleclanlogo_enabled = false;
ace_vehicles_hideEjectAction = true;
force ace_vehicles_keepEngineRunning = false;
ace_vehicles_speedLimiterStep = 5;
force ace_viewports_enabled = true;

// ACE Fahrzeugsperre
force ace_vehiclelock_defaultLockpickStrength = 10;
force ace_vehiclelock_lockVehicleInventory = false;
force ace_vehiclelock_vehicleStartingLockState = -1;

// ACE Feld Rationen
force ace_field_rations_zeusUpdates = false;
force acex_field_rations_affectAdvancedFatigue = true;
force acex_field_rations_enabled = true;
acex_field_rations_hudShowLevel = 0;
acex_field_rations_hudTransparency = -1;
acex_field_rations_hudType = 0;
force acex_field_rations_hungerSatiated = 2;
force acex_field_rations_terrainObjectActions = true;
force acex_field_rations_thirstQuenched = 2;
force acex_field_rations_timeWithoutFood = 3;
force acex_field_rations_timeWithoutWater = 3;
force acex_field_rations_waterSourceActions = 2;

// ACE Feuer
force ace_fire_dropWeapon = 1;
force ace_fire_enabled = true;
force ace_fire_enableFlare = false;
ace_fire_enableScreams = true;

// ACE Fingerzeig
force ace_finger_enabled = true;
ace_finger_indicatorColor = [0.83,0.68,0.21,0.75];
force ace_finger_indicatorForSelf = true;
force ace_finger_maxRange = 6;
force ace_finger_proximityScaling = true;
force ace_finger_sizeCoef = 1;

// ACE G-Kräfte
force ace_gforces_coef = 1;
force ace_gforces_enabledFor = 1;

// ACE Gefangene
force ace_captives_allowHandcuffOwnSide = true;
force ace_captives_allowSurrender = true;
force ace_captives_requireSurrender = 1;
force ace_captives_requireSurrenderAi = false;

// ACE Gehör
force ace_hearing_autoAddEarplugsToUnits = 1;
ace_hearing_disableEarRinging = false;
force ace_hearing_earplugsVolume = 0.5;
force ace_hearing_enableCombatDeafness = true;
force ace_hearing_enabledForZeusUnits = true;
ace_hearing_enableNoiseDucking = true;
force ace_hearing_explosionDeafnessCoefficient = 0.495006;
force ace_hearing_unconsciousnessVolume = 0.4;

// ACE Gräben
force ace_trenches_bigEnvelopeDigDuration = 25;
force ace_trenches_bigEnvelopeRemoveDuration = 15;
force ace_trenches_smallEnvelopeDigDuration = 20;
force ace_trenches_smallEnvelopeRemoveDuration = 12;

// ACE Granaten
force ace_grenades_convertExplosives = true;

// ACE Headless
force acex_headless_delay = 15;
force acex_headless_enabled = false;
force acex_headless_endMission = 0;
force acex_headless_log = false;
force acex_headless_transferLoadout = 0;

// ACE Heißlaufen
force ace_overheating_cookoffCoef = 1;
force ace_overheating_coolingCoef = 1.5;
ace_overheating_displayTextOnJam = true;
force ace_overheating_enabled = true;
force ace_overheating_heatCoef = 1;
force ace_overheating_jamChanceCoef = 1;
force ace_overheating_overheatingDispersion = true;
force ace_overheating_overheatingRateOfFire = true;
force ace_overheating_particleEffectsAndDispersionDistance = 29.6891;
force ace_overheating_showParticleEffects = true;
force ace_overheating_showParticleEffectsForEveryone = true;
force ace_overheating_suppressorCoef = 0.6;
force ace_overheating_unJamFailChance = 0.1;
force ace_overheating_unJamOnreload = false;
force ace_overheating_unJamOnSwapBarrel = false;

// ACE Hinsetzen
force acex_sitting_enable = true;

// ACE Interaktion
force ace_interaction_disableNegativeRating = false;
force ace_interaction_enableAnimActions = true;
force ace_interaction_enableGroupRenaming = true;
ace_interaction_enableMagazinePassing = true;
force ace_interaction_enableTeamManagement = true;
ace_interaction_enableThrowablePassing = true;
ace_interaction_enableWeaponAttachments = true;
force ace_interaction_interactWithEnemyCrew = 0;
force ace_interaction_interactWithTerrainObjects = false;
force ace_interaction_remoteTeamManagement = true;

// ACE Interaktionsmenü
ace_gestures_showOnInteractionMenu = 2;
ace_interact_menu_actionOnKeyRelease = true;
ace_interact_menu_addBuildingActions = false;
ace_interact_menu_alwaysUseCursorInteraction = false;
ace_interact_menu_alwaysUseCursorSelfInteraction = true;
ace_interact_menu_colorShadowMax = [0,0,0,1];
ace_interact_menu_colorShadowMin = [0,0,0,0.25];
ace_interact_menu_colorTextMax = [1,1,1,1];
ace_interact_menu_colorTextMin = [1,1,1,0.25];
ace_interact_menu_consolidateSingleChild = false;
ace_interact_menu_cursorKeepCentered = false;
ace_interact_menu_cursorKeepCenteredSelfInteraction = false;
ace_interact_menu_menuAnimationSpeed = 0;
ace_interact_menu_menuBackground = 0;
ace_interact_menu_menuBackgroundSelf = 0;
ace_interact_menu_selectorColor = [1,0,0];
ace_interact_menu_shadowSetting = 2;
ace_interact_menu_textSize = 2;
ace_interact_menu_useListMenu = true;
ace_interact_menu_useListMenuSelf = false;

// ACE Interaktionsmenü (selbst) - Mehr
ace_interact_menu_more__ACE_CheckAirTemperature = false;
ace_interact_menu_more__ace_csw_deploy = false;
ace_interact_menu_more__ACE_Equipment = false;
ace_interact_menu_more__ACE_Explosives = false;
ace_interact_menu_more__ace_field_rations = false;
ace_interact_menu_more__ace_fortify = false;
ace_interact_menu_more__ace_gestures = false;
ace_interact_menu_more__ace_intelitems = false;
ace_interact_menu_more__ACE_MapFlashlight = false;
ace_interact_menu_more__ACE_MapGpsHide = false;
ace_interact_menu_more__ACE_MapGpsShow = false;
ace_interact_menu_more__ACE_MapTools = false;
ace_interact_menu_more__ACE_Medical = false;
ace_interact_menu_more__ace_medical_ai_heal = false;
ace_interact_menu_more__ACE_Medical_Menu = false;
ace_interact_menu_more__ACE_MoveRallypoint = false;
ace_interact_menu_more__ACE_PlottingBoard = false;
ace_interact_menu_more__ACE_PlottingBoardHide = false;
ace_interact_menu_more__ACE_RepackMagazines = false;
ace_interact_menu_more__ace_sandbag_place = false;
ace_interact_menu_more__ACE_StartSurrenderingSelf = false;
ace_interact_menu_more__ACE_StopEscortingSelf = false;
ace_interact_menu_more__ACE_StopSurrenderingSelf = false;
ace_interact_menu_more__ACE_Tags = false;
ace_interact_menu_more__ACE_TeamManagement = false;
ace_interact_menu_more__ace_zeus_create = false;
ace_interact_menu_more__ace_zeus_delete = false;
ace_interact_menu_more__aceax_ingame_gear = false;
ace_interact_menu_more__acex_sitting_Stand = false;
ace_interact_menu_more__ACRE_Interact = false;
ace_interact_menu_more__acre_sys_zeus_playerEars = false;
ace_interact_menu_more__acre_sys_zeus_remoteEars = false;
ace_interact_menu_more__KAT_Equipment = false;
ace_interact_menu_more__Medical = false;
ace_interact_menu_more__SSS_main = false;
ace_interact_menu_more__stx_civilians_shoo = false;
ace_interact_menu_more__stx_logistics_canteenSip = false;
ace_interact_menu_more__stx_logistics_deployResupply = false;
ace_interact_menu_more__TFAR_Radio = false;

// ACE Interaktionsmenü (selbst) - Zu Ursprung bewegen
ace_interact_menu_moveToRoot__ACE_Equipment__ace_atragmx_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_attach_Attach = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_attach_Detach = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_CheckDogtags = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_Chemlights = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_dagr_menu = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_dagr_menu__ace_dagr_toggle = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_flags = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_flags__ace_flags_furlFlag = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_goggles_wipeGlasses = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_status = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_weaponOff = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_weaponSwap = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_weaponTo = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_huntir_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_interaction_weaponAttachments = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_kestrel4500_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_kestrel4500_open__ace_kestrel4500_hide = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_kestrel4500_open__ace_kestrel4500_show = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_marker_flags = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_microdagr_configure = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_microdagr_configure__ace_microdagr_close = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_microdagr_configure__ace_microdagr_show = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_activate = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_connectHeadphones = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_deactivate = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_disconnectHeadphones = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_mk6mortar_rangetable = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_CheckTemperature = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_CheckTemperatureSpareBarrels = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_CoolWeaponWithItem = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_SwapBarrel = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_UnJam = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_PutInEarplugs = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_PutOnEHP = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_rangecard_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_rangecard_open__ace_rangecard_makeCopy = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_rangecard_open__ace_rangecard_openCopy = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_reload_checkAmmo = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_RemoveEarplugs = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_RemoveEHP = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_scopes_adjustZero = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_scopes_resetZero = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_spottingscope_place = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_TacticalLadders = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__ace_trenches_digEnvelopeBig = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__ace_trenches_digEnvelopeSmall = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeGiant = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeLongNameEmplacment = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeShort = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeVehicle = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_tripod_place = false;
ace_interact_menu_moveToRoot__ACE_Equipment__acre_sys_gsa_placeSpike = false;
ace_interact_menu_moveToRoot__ACE_Equipment__acre_sys_gsa_placeSpikeMast = false;
ace_interact_menu_moveToRoot__ACE_Equipment__bocr_main_cutLoweringLine = false;
ace_interact_menu_moveToRoot__ACE_Equipment__bocr_main_lower = false;
ace_interact_menu_moveToRoot__ACE_Equipment__bocr_main_onBack = false;
ace_interact_menu_moveToRoot__ACE_Equipment__bocr_main_onChest = false;
ace_interact_menu_moveToRoot__ACE_Equipment__bocr_main_swap = false;
ace_interact_menu_moveToRoot__ACE_Equipment__RR_mapStuff_mapPut = false;
ace_interact_menu_moveToRoot__ACE_Explosives__ACE_Cellphone = false;
ace_interact_menu_moveToRoot__ACE_Explosives__ACE_Place = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Advance = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_CeaseFire = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Cover = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Engage = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Follow = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Forward = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Freeze = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Go = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Hold = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Point = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Regroup = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Stop = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Up = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Warning = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignCompass = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignNorth = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignToPlottingBoard = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignToPlottingBoardAcrylic = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignToPlottingBoardRuler = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsHide = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsShowNormal = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsShowSmall = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_ArmLeft = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_ArmRight = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_Head = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_LegLeft = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_LegRight = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_Torso = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_Torso__TriageCard = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignAcrylic = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignAcrylic__ACE_PlottingBoardAlignAcrylicMaptool = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignAcrylic__ACE_PlottingBoardAlignAcrylicUp = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignBoard = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignBoard__ACE_PlottingBoardAlignBoardMaptool = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignBoard__ACE_PlottingBoardAlignBoardUp = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignRuler = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignRuler__ACE_PlottingBoardAlignRulerMaptool = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignRuler__ACE_PlottingBoardAlignRulerUp = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardRulerHide = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardRulerShow = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardWipe = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_BecomeLeader = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamBlue = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamGreen = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamMain = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamRed = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamYellow = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_LeaveGroup = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_remoteTeamManagement = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_RenameGroup = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__diwako_dui_buddy_buddy_action_team_remove = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__SNC_Groupmanager = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Doctor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Doctor_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Kat = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Kat_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Medic = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Medic_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__RedCross = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__RedCross_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Doctor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Doctor_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Kat = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Kat_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Medic = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Medic_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__RedCross = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__RedCross_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Doctor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Doctor_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Kat = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Kat_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Medic = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Medic_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__RedCross = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__RedCross_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Doctor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Doctor_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Kat = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Kat_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Medic = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Medic_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__RedCross = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__RedCross_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__UnSlingLeftArm = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__UnSlingLeftLeg = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__UnSlingRightArm = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__UnSlingRightLeg = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Attach_PersonalOxygen = false;
ace_interact_menu_moveToRoot__KAT_Equipment__BubbleWrapPopping = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Check_PersonalOxygen = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Detach_PersonalOxygen = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AED_X_Interactions = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AED_X_Interactions__KAT_AED_X_addSound = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AED_X_Interactions__KAT_AED_X_removeSound = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AED_X_Interactions__KAT_AED_X_ViewMonitor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__AFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot5 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot6 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__AFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot1_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot2_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot3_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot4_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot5 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot5_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot6 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot6_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChangeGasMaskFilter = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_CheckGasMaskDur = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_CheckHandWarmersSelf = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChemicalDetector = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChemicalDetector__KAT_ChemicalDetector_Enable = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChemicalDetector__KAT_ChemicalDetector_SoundOff = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChemicalDetector__KAT_ChemicalDetector_SoundOn = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_DeployStretcher = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__IFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__IFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot1_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot2_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot3_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot4_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__MFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot5 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot6 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot7 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot8 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__MFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot1_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot2_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot3_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot4_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot5 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot5_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot6 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot6_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot7 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot7_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot8 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot8_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_placeAED = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_placeAEDX = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_PutOnGasMask = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_TakeOffGasMask = false;
ace_interact_menu_moveToRoot__KAT_Equipment__openCrossPanel = false;
ace_interact_menu_moveToRoot__KAT_Equipment__PulseOximeter_addSound = false;
ace_interact_menu_moveToRoot__KAT_Equipment__PulseOximeter_removeSound = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Refill_OxygenTank_150_Facility = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Refill_OxygenTank_300_Facility = false;
ace_interact_menu_moveToRoot__KAT_Equipment__SetPreferred_OxygenTank_150 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__SetPreferred_OxygenTank_300 = false;
ace_interact_menu_moveToRoot__Medical__ACE_Head = false;
ace_interact_menu_moveToRoot__Medical__ACE_Head__CheckBloodPressure = false;
ace_interact_menu_moveToRoot__SSS_main__SSS_artillery = false;
ace_interact_menu_moveToRoot__SSS_main__SSS_CAS = false;
ace_interact_menu_moveToRoot__SSS_main__SSS_logistics = false;
ace_interact_menu_moveToRoot__SSS_main__SSS_transport = false;
ace_interact_menu_moveToRoot__TFAR_Radio__ADDON_EXCEPT = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__Load_All = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__Load_Root = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__Load_Root__Load_All = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__Load_Root__Load_LR = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__Load_Root__Load_SR = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__Load_Root__Load_VLR = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__LR_Root = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__LR_Root__LR_Load = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__LR_Root__LR_Save = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__Save_Root = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__Save_Root__Save_LR = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__Save_Root__Save_SR = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__Save_Root__Save_VLR = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__SR_Root = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__SR_Root__SR_Load = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__SR_Root__SR_Save = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__VLR_Root = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__VLR_Root__LR_Load = false;
ace_interact_menu_moveToRoot__TFAR_Radio__TFAR_Setter__VLR_Root__LR_Save = false;

// ACE Karte
force ace_map_BFT_Enabled = false;
force ace_map_BFT_HideAiGroups = false;
force ace_map_BFT_Interval = 1;
force ace_map_BFT_ShowPlayerNames = false;
force ace_map_DefaultChannel = -1;
force ace_map_mapGlow = true;
force ace_map_mapIllumination = true;
force ace_map_mapLimitZoom = false;
force ace_map_mapShake = true;
force ace_map_mapShowCursorCoordinates = false;
ace_markers_moveRestriction = 0;
ace_markers_timestampEnabled = true;
ace_markers_timestampFormat = "HH:MM";
ace_markers_timestampHourFormat = 24;
force ace_markers_timestampTimezone = 0;
ace_markers_TimestampUTCMinutesOffset = 0;
force ace_markers_timestampUTCOffset = 0;

// ACE Kartenwerkzeug
ace_maptools_drawStraightLines = true;
ace_maptools_plottingBoardAllowChannelDrawing = 1;
ace_maptools_rotateModifierKey = 1;

// ACE Kartenzeichen
ace_map_gestures_allowCurator = true;
ace_map_gestures_allowSpectator = true;
ace_map_gestures_briefingMode = 0;
ace_map_gestures_defaultColor = [1,0.88,0,0.7];
ace_map_gestures_defaultLeadColor = [1,0.88,0,0.95];
force ace_map_gestures_enabled = true;
force ace_map_gestures_interval = 0.03;
force ace_map_gestures_maxRange = 7;
force ace_map_gestures_maxRangeCamera = 14;
ace_map_gestures_nameTextColor = [0.2,0.2,0.2,0.3];
force ace_map_gestures_onlyShowFriendlys = false;

// ACE KI
force ace_ai_assignNVG = false;

// ACE Lautstärke
acex_volume_enabled = false;
acex_volume_fadeDelay = 1;
acex_volume_lowerInVehicles = false;
acex_volume_reduction = 5;
acex_volume_remindIfLowered = false;
acex_volume_showNotification = true;

// ACE Logistik
ace_cargo_carryAfterUnload = true;
force ace_cargo_checkSizeInteraction = true;
force ace_cargo_enable = true;
force ace_cargo_enableDeploy = true;
ace_cargo_enableRename = true;
force ace_cargo_loadTimeCoefficient = 5;
ace_cargo_openAfterUnload = 0;
force ace_cargo_paradropTimeCoefficent = 2.5;
force ace_rearm_distance = 20;
force ace_rearm_enabled = true;
force ace_rearm_level = 1;
force ace_rearm_supply = 0;
force ace_refuel_cargoRate = 10;
force ace_refuel_enabled = true;
force ace_refuel_hoseLength = 12;
force ace_refuel_progressDuration = 1;
force ace_refuel_rate = 1;
force ace_towing_addRopeToVehicleInventory = true;

// ACE Magazine umpacken
ace_magazinerepack_repackAnimation = true;
ace_magazinerepack_repackLoadedMagazines = true;
force ace_magazinerepack_timePerAmmo = 1.5;
force ace_magazinerepack_timePerBeltLink = 8;
force ace_magazinerepack_timePerMagazine = 2;

// ACE Patronenhülsen
force ace_casings_enabled = true;
force ace_casings_maxCasings = 120;

// ACE Reparieren
force ace_repair_addSpareParts = true;
force ace_repair_autoShutOffEngineWhenStartingRepair = false;
force ace_repair_consumeItem_toolKit = 0;
force ace_repair_displayTextOnRepair = true;
force ace_repair_enabled = true;
force ace_repair_engineerSetting_fullRepair = 1;
force ace_repair_engineerSetting_repair = 1;
force ace_repair_engineerSetting_wheel = 0;
force ace_repair_fullRepairLocation = 3;
force ace_repair_fullRepairRequiredItems = ["ace_repair_anyToolKit"];
force ace_repair_locationsBoostTraining = true;
force ace_repair_miscRepairRequiredItems = ["ace_repair_anyToolKit"];
force ace_repair_miscRepairTime = 15;
force ace_repair_patchWheelEnabled = 0;
force ace_repair_patchWheelLocation = ["ground","vehicle"];
force ace_repair_patchWheelMaximumRepair = 0.3;
force ace_repair_patchWheelRequiredItems = ["ace_repair_anyToolKit"];
force ace_repair_patchWheelTime = 5;
force ace_repair_repairDamageThreshold = 0.6;
force ace_repair_repairDamageThreshold_engineer = 0.4;
force ace_repair_timeCoefficientFullRepair = 1.5;
force ace_repair_wheelChangeTime = 10;
force ace_repair_wheelRepairRequiredItems = [];

// ACE Schnellzugang
force ace_quickmount_distance = 3;
force ace_quickmount_enabled = true;
ace_quickmount_enableMenu = 3;
ace_quickmount_priority = 0;
force ace_quickmount_speed = 18;

// ACE Schutzbrille
force ace_goggles_drawOverlay = true;
force ace_goggles_effects = 2;
force ace_goggles_showClearGlasses = false;
force ace_goggles_showInThirdPerson = false;

// ACE Sichteinschränkungen
force acex_viewrestriction_mode = 0;
force acex_viewrestriction_modeSelectiveAir = 0;
force acex_viewrestriction_modeSelectiveFoot = 0;
force acex_viewrestriction_modeSelectiveLand = 0;
force acex_viewrestriction_modeSelectiveSea = 0;
acex_viewrestriction_preserveView = false;

// ACE Sichtweitenbegrenzung
force ace_viewdistance_enabled = true;
force ace_viewdistance_limitViewDistance = 10000;
ace_viewdistance_objectViewDistanceCoeff = 0;
ace_viewdistance_viewDistanceAirVehicle = 0;
ace_viewdistance_viewDistanceLandVehicle = 0;
ace_viewdistance_viewDistanceOnFoot = 0;

// ACE Splittersimulation
force ace_frag_enabled = true;
force ace_frag_reflectionsEnabled = false;
force ace_frag_spallEnabled = false;
force ace_frag_spallIntensity = 1;

// ACE Sprengstoffe
ace_explosives_customTimerDefault = 30;
force ace_explosives_customTimerMax = 900;
force ace_explosives_customTimerMin = 5;
force ace_explosives_explodeOnDefuse = false;
force ace_explosives_punishNonSpecialists = false;
force ace_explosives_requireSpecialist = true;

// ACE TFAR Radio Setter
TFAR_Setter_Layout = false;
TFAR_Setter_Shortcut = false;
TFAR_Setter_ShowLR = true;
TFAR_Setter_ShowSR = true;
TFAR_Setter_ShowVLR = true;

// ACE Unkategorisiert
force ace_fastroping_autoAddFRIES = false;
force ace_fastroping_requireRopeItems = false;
ace_flags_enableCarrying = true;
ace_flags_enablePlacing = true;
force ace_gunbag_swapGunbagEnabled = true;
force ace_hitreactions_minDamageToTrigger = 0.1;
force ace_hitreactions_weaponDropChanceArmHitAI = 0;
force ace_hitreactions_weaponDropChanceArmHitPlayer = 0;
ace_inventory_inventoryDisplaySize = 0;
force ace_laser_dispersionCount = 2;
force ace_laser_showLaserOnMap = 1;
force ace_marker_flags_placeAnywhere = false;
force ace_microdagr_mapDataAvailable = 2;
force ace_microdagr_waypointPrecision = 3;
force ace_noradio_enabled = true;
ace_optionsmenu_showNewsOnMainMenu = true;
force ace_overpressure_backblastDistanceCoefficient = 1;
force ace_overpressure_overpressureDistanceCoefficient = 1;
force ace_parachute_failureChance = 0;
ace_parachute_hideAltimeter = true;
ace_tagging_quickTag = 1;

// ACE Verstärken
force ace_fortify_markObjectsOnMap = 1;
force ace_fortify_timeCostCoefficient = 1;
force ace_fortify_timeMin = 1.5;
acex_fortify_settingHint = 2;

// ACE Waffen
ace_common_persistentLaserEnabled = false;
ace_reload_displayText = true;
ace_reload_showCheckAmmoSelf = false;
ace_reloadlaunchers_displayStatusText = true;
ace_weaponselect_displayText = true;

// ACE Wetter
force ace_weather_enabled = true;
ace_weather_showCheckAirTemperature = true;
force ace_weather_updateInterval = 60;
force ace_weather_windSimulation = true;

// ACE Wiedereinstieg
force ace_respawn_removeDeadBodiesDisconnected = true;
force ace_respawn_savePreDeathGear = false;

// ACE Windablenkung
force ace_winddeflection_enabled = true;
force ace_winddeflection_simulationInterval = 0.05;
force ace_winddeflection_vehicleEnabled = true;

// ACE Zeige Spielernamen
force ace_nametags_ambientBrightnessAffectViewDist = 1;
ace_nametags_defaultNametagColor = [0.77,0.51,0.08,1];
ace_nametags_nametagColorBlue = [0.67,0.67,1,1];
ace_nametags_nametagColorGreen = [0.67,1,0.67,1];
ace_nametags_nametagColorMain = [1,1,1,1];
ace_nametags_nametagColorRed = [1,0.67,0.67,1];
ace_nametags_nametagColorYellow = [1,1,0.67,1];
force ace_nametags_playerNamesMaxAlpha = 0.8;
force ace_nametags_playerNamesViewDistance = 5;
force ace_nametags_showCursorTagForVehicles = false;
ace_nametags_showNamesForAI = false;
ace_nametags_showPlayerNames = 1;
ace_nametags_showPlayerRanks = true;
ace_nametags_showSoundWaves = 1;
ace_nametags_showVehicleCrewInfo = true;
ace_nametags_tagSize = 2;

// ACE Zeus
force ace_zeus_autoAddObjects = false;
force ace_zeus_canCreateZeus = -1;
force ace_zeus_radioOrdnance = false;
force ace_zeus_remoteWind = false;
force ace_zeus_revealMines = 0;
force ace_zeus_zeusAscension = false;
force ace_zeus_zeusBird = false;

// ACE Ziehen
force ace_dragging_allowRunWithLightweight = true;
ace_dragging_dragAndFire = true;
force ace_dragging_skipContainerWeight = false;
force ace_dragging_weightCoefficient = 1;

// ACE Zielfernrohre
force ace_scopes_correctZeroing = true;
force ace_scopes_deduceBarometricPressureFromTerrainAltitude = false;
force ace_scopes_defaultZeroRange = 100;
force ace_scopes_enabled = true;
force ace_scopes_forceUseOfAdjustmentTurrets = false;
ace_scopes_inScopeAdjustment = false;
force ace_scopes_overwriteZeroRange = false;
force ace_scopes_simplifiedZeroing = false;
ace_scopes_useLegacyUI = false;
force ace_scopes_zeroReferenceBarometricPressure = 1013.25;
force ace_scopes_zeroReferenceHumidity = 0;
force ace_scopes_zeroReferenceTemperature = 15;

// ACE Zuschauer
force ace_spectator_enableAI = false;
ace_spectator_maxFollowDistance = 5;
force ace_spectator_restrictModes = 0;
force ace_spectator_restrictVisions = 0;

// ACE-Arsenal
force ace_arsenal_allowDefaultLoadouts = true;
force ace_arsenal_allowSharedLoadouts = true;
ace_arsenal_camInverted = false;
ace_arsenal_defaultToFavorites = false;
force ace_arsenal_enableIdentityTabs = true;
ace_arsenal_enableModIcons = 1;
ace_arsenal_EnableRPTLog = false;
ace_arsenal_favoritesColor = [0.9,0.875,0.6];
ace_arsenal_fontHeight = 4.5;
ace_arsenal_loadoutsSaveFace = false;
ace_arsenal_loadoutsSaveInsignia = true;
ace_arsenal_loadoutsSaveVoice = false;
ace_arsenal_showUnavailableItems = 0;

// ACE-Medicsystem
force ace_medical_ai_enabledFor = 2;
force ace_medical_ai_requireItems = 0;
force ace_medical_AIDamageThreshold = 1;
force ace_medical_bleedingCoefficient = 1;
force ace_medical_blood_bloodLifetime = 600;
force ace_medical_blood_enabledFor = 2;
force ace_medical_blood_maxBloodObjects = 300;
force ace_medical_deathChance = 0.4;
force ace_medical_dropWeaponUnconsciousChance = 0;
force ace_medical_enableVehicleCrashes = true;
force ace_medical_engine_damagePassThroughEffect = 1;
force ace_medical_fatalDamageSource = 2;
force ace_medical_fractureChance = 0.8;
force ace_medical_fractures = 3;
force ace_medical_ivFlowRate = 1;
force ace_medical_limbDamageThreshold = 5;
force ace_medical_limping = 1;
force ace_medical_painCoefficient = 1;
force ace_medical_painUnconsciousChance = 0.1;
force ace_medical_painUnconsciousThreshold = 0.5;
force ace_medical_playerDamageThreshold = 1;
force ace_medical_spontaneousWakeUpChance = 0.1;
force ace_medical_spontaneousWakeUpEpinephrineBoost = 1.5;
force ace_medical_statemachine_AIUnconsciousness = true;
force ace_medical_statemachine_cardiacArrestBleedoutEnabled = true;
force ace_medical_statemachine_cardiacArrestTime = 600;
force ace_medical_statemachine_fatalInjuriesAI = 0;
force ace_medical_statemachine_fatalInjuriesPlayer = 0;
force ace_medical_useLimbDamage = 0;
force ace_medical_vitals_simulateSpO2 = true;

// ACE-Medicsystem Behandlung
force ace_medical_treatment_advancedBandages = 2;
force ace_medical_treatment_advancedDiagnose = 1;
force ace_medical_treatment_advancedMedication = true;
force ace_medical_treatment_allowBodyBagUnconscious = false;
force ace_medical_treatment_allowGraveDigging = 1;
force ace_medical_treatment_allowLitterCreation = true;
force ace_medical_treatment_allowSelfIV = 1;
force ace_medical_treatment_allowSelfPAK = 1;
force ace_medical_treatment_allowSelfStitch = 1;
force ace_medical_treatment_allowSharedEquipment = 0;
force ace_medical_treatment_bandageEffectiveness = 1;
force ace_medical_treatment_bandageRollover = true;
force ace_medical_treatment_clearTrauma = 1;
force ace_medical_treatment_consumePAK = 0;
force ace_medical_treatment_consumeSurgicalKit = 0;
force ace_medical_treatment_convertItems = 0;
force ace_medical_treatment_cprSuccessChanceMax = 0.5;
force ace_medical_treatment_cprSuccessChanceMin = 0.4;
force ace_medical_treatment_graveDiggingMarker = true;
force ace_medical_treatment_holsterRequired = 0;
force ace_medical_treatment_litterCleanupDelay = 600;
force ace_medical_treatment_locationAdenosine = 0;
force ace_medical_treatment_locationEpinephrine = 0;
force ace_medical_treatment_locationIV = 0;
force ace_medical_treatment_locationMorphine = 0;
force ace_medical_treatment_locationPAK = 2;
force ace_medical_treatment_locationsBoostTraining = true;
force ace_medical_treatment_locationSplint = 0;
force ace_medical_treatment_locationSurgicalKit = 0;
force ace_medical_treatment_maxLitterObjects = 500;
force ace_medical_treatment_medicAdenosine = 0;
force ace_medical_treatment_medicEpinephrine = 0;
force ace_medical_treatment_medicIV = 0;
force ace_medical_treatment_medicMorphine = 0;
force ace_medical_treatment_medicPAK = 0;
force ace_medical_treatment_medicSplint = 0;
force ace_medical_treatment_medicSurgicalKit = 1;
force ace_medical_treatment_numericalPulse = 1;
force ace_medical_treatment_timeCoefficientPAK = 1;
force ace_medical_treatment_treatmentTimeAutoinjector = 5;
force ace_medical_treatment_treatmentTimeBodyBag = 15;
force ace_medical_treatment_treatmentTimeCoeffZeus = 1;
force ace_medical_treatment_treatmentTimeCPR = 15;
force ace_medical_treatment_treatmentTimeGrave = 30;
force ace_medical_treatment_treatmentTimeIV = 12;
force ace_medical_treatment_treatmentTimeSplint = 7;
force ace_medical_treatment_treatmentTimeTourniquet = 7;
force ace_medical_treatment_woundReopenChance = 1;
force ace_medical_treatment_woundStitchTime = 5;

// ACE-Medicsystem Interface
ace_medical_feedback_bloodVolumeEffectType = 0;
ace_medical_feedback_enableHUDIndicators = true;
ace_medical_feedback_painEffectType = 1;
ace_medical_gui_bloodLossColor_0 = [1,1,1,1];
ace_medical_gui_bloodLossColor_1 = [1,0.94,0.48,1];
ace_medical_gui_bloodLossColor_2 = [1,0.87,0.25,1];
ace_medical_gui_bloodLossColor_3 = [1,0.79,0.17,1];
ace_medical_gui_bloodLossColor_4 = [1,0.71,0.11,1];
ace_medical_gui_bloodLossColor_5 = [1,0.62,0.05,1];
ace_medical_gui_bloodLossColor_6 = [1,0.53,0.01,1];
ace_medical_gui_bloodLossColor_7 = [1,0.42,0,1];
ace_medical_gui_bloodLossColor_8 = [1,0.29,0,1];
ace_medical_gui_bloodLossColor_9 = [1,0,0,1];
ace_medical_gui_bodyPartOutlineColor = [1,1,1,1];
ace_medical_gui_damageColor_0 = [1,1,1,1];
ace_medical_gui_damageColor_1 = [0.52,0.73,1,1];
ace_medical_gui_damageColor_2 = [0.38,0.68,1,1];
ace_medical_gui_damageColor_3 = [0.37,0.6,1,1];
ace_medical_gui_damageColor_4 = [0.35,0.53,1,1];
ace_medical_gui_damageColor_5 = [0.33,0.45,1,1];
ace_medical_gui_damageColor_6 = [0.3,0.37,1,1];
ace_medical_gui_damageColor_7 = [0.25,0.29,1,1];
ace_medical_gui_damageColor_8 = [0.18,0.18,1,1];
ace_medical_gui_damageColor_9 = [0,0,1,1];
ace_medical_gui_enableActions = 0;
ace_medical_gui_enableMedicalMenu = 1;
ace_medical_gui_enableSelfActions = true;
ace_medical_gui_interactionMenuShowTriage = 1;
force ace_medical_gui_maxDistance = 4.0031;
ace_medical_gui_openAfterTreatment = true;
ace_medical_gui_peekMedicalInfoReleaseDelay = 1;
ace_medical_gui_peekMedicalOnHit = false;
ace_medical_gui_peekMedicalOnHitDuration = 1;
force ace_medical_gui_showBleeding = 2;
force ace_medical_gui_showBloodlossEntry = true;
force ace_medical_gui_showDamageEntry = false;
ace_medical_gui_tourniquetWarning = false;

// ACE-Nachtsicht
force ace_nightvision_aimDownSightsBlur = 1;
force ace_nightvision_disableNVGsWithSights = false;
force ace_nightvision_effectScaling = 1;
force ace_nightvision_fogScaling = 1;
force ace_nightvision_noiseScaling = 1;
ace_nightvision_shutterEffects = true;

// ACRE2
acre_sys_core_automaticAntennaDirection = false;
acre_sys_core_defaultRadioVolume = 0.8;
force acre_sys_core_fullDuplex = false;
acre_sys_core_godVolume = 1;
force acre_sys_core_ignoreAntennaDirection = false;
force acre_sys_core_interference = true;
acre_sys_core_postmixGlobalVolume = 1;
acre_sys_core_premixGlobalVolume = 1;
force acre_sys_core_revealToAI = 1;
acre_sys_core_spectatorVolume = 1;
force acre_sys_core_terrainLoss = 1;
force acre_sys_core_ts3ChannelName = "ACRE";
force acre_sys_core_ts3ChannelPassword = "123";
acre_sys_core_ts3ChannelSwitch = true;
acre_sys_core_unmuteClients = true;
force acre_sys_radio_defaultRadio = "ACRE_PRC343";
force acre_sys_signal_signalModel = 2;

// ACRE2 Gesten
acre_sys_gestures_enabled = true;
force acre_sys_gestures_showConnectorRopes = true;
acre_sys_gestures_stopADS = false;

// ACRE2 Nutzeroberfläche
acre_sys_godmode_rxNotification = true;
acre_sys_godmode_rxNotificationColor = [0.8,0.8,0.8,1];
acre_sys_godmode_txNotification = true;
acre_sys_godmode_txNotificationCurrentChatColor = [0.8,0.8,0.8,1];
acre_sys_godmode_txNotificationGroup1Color = [0.8,0.8,0.8,1];
acre_sys_godmode_txNotificationGroup2Color = [0.8,0.8,0.8,1];
acre_sys_godmode_txNotificationGroup3Color = [0.8,0.8,0.8,1];
acre_sys_gui_volumeColorScale = [[1,1,0,0.5],[1,0.83,0,0.5],[1,0.65,0,0.5],[1,0.44,0,0.5],[1,0,0,0.5]];
acre_sys_list_CycleRadiosColor = [0.66,0.05,1,1];
acre_sys_list_DefaultPTTColor = [1,0.8,0,1];
acre_sys_list_HintBackgroundColor = [0,0,0,0.8];
acre_sys_list_HintTextFont = "RobotoCondensed";
acre_sys_list_LanguageColor = [1,0.29,0.16,1];
acre_sys_list_LanguageHintPersist = true;
acre_sys_list_PTT1Color = [1,0.8,0,1];
acre_sys_list_PTT2Color = [1,0.8,0,1];
acre_sys_list_PTT3Color = [1,0.8,0,1];
acre_sys_list_SwitchChannelColor = [0.66,0.05,1,1];
acre_sys_list_ToggleHeadsetColor = [0.66,0.05,1,1];

// ACRE2 Zeus
acre_sys_zeus_zeusCanSpectate = true;
acre_sys_zeus_zeusCommunicateViaCamera = true;
acre_sys_zeus_zeusDefaultVoiceSource = false;

// Backpack On Chest
force bocr_main_disabled = false;
force bocr_main_walk = true;

// BettIR
BettIR_ViewDistance = 300;

// Boxloader
force boxloader_allrepair_height = 5;
force boxloader_allrepair_load = true;
force boxloader_allrepair_push = 10000;
force boxloader_allrepair_weight = 10000;
force boxloader_allrepair_work = true;
force boxloader_fort_allow_floating = false;
boxloader_fort_snap_editor = false;
force boxloader_hidecargo_enabled = false;
force boxloader_maxload_enabled = false;
force boxloader_maxload_lift = 50;
force boxloader_maxload_minpush = 10;
force boxloader_maxload_overhead = 30;
force boxloader_maxload_push = 200;
force boxloader_maxunload_enabled = false;
force boxloader_preciseunload_enabled = false;
force boxloader_push_enabled = true;
force boxloader_retrofit_enabled = true;
force boxloader_tractor_bulldoze = false;
force boxloader_tractor_bulldoze_fence = false;
force boxloader_tractor_bulldoze_hide = false;
force boxloader_tractor_bulldoze_ruins = false;
force boxloader_tractor_bulldoze_wall = false;

// Bundeswehr
BWA3_Leopard_ClocknumbersDir_Commander = false;
BWA3_NaviPad_showMembers = true;
BWA3_Puma_ClocknumbersDir_Commander = false;
BWA3_Puma_ClocknumbersDir_Gunner = false;

// CF_BAI
force CF_BAI_subskills_maximum_aimingAccuracy = 0.852272;
force CF_BAI_subskills_maximum_aimingShake = 0.500746;
force CF_BAI_subskills_maximum_aimingSpeed = 0.299874;
force CF_BAI_subskills_maximum_commanding = 1;
force CF_BAI_subskills_maximum_courage = 0.500746;
force CF_BAI_subskills_maximum_general = 0.500746;
force CF_BAI_subskills_maximum_reloadSpeed = 0;
force CF_BAI_subskills_maximum_spotDistance = 1;
force CF_BAI_subskills_maximum_spotTime = 0.802054;
force CF_BAI_subskills_minimum_aimingAccuracy = 0.598067;
force CF_BAI_subskills_minimum_aimingShake = 0.5;
force CF_BAI_subskills_minimum_aimingSpeed = 0.5;
force CF_BAI_subskills_minimum_commanding = 0.5;
force CF_BAI_subskills_minimum_courage = 0.299773;
force CF_BAI_subskills_minimum_general = 1;
force CF_BAI_subskills_minimum_reloadSpeed = 0.5;
force CF_BAI_subskills_minimum_spotDistance = 0.6975;
force CF_BAI_subskills_minimum_spotTime = 0.5;
force CF_BAI_subskills_sleep = 30;
force CF_BAI_subskills_terrain_maximum_default = 30;
force CF_BAI_subskills_terrain_maximum_world_code = "[[""pja310"",25],[""Panthera3"",25]]";
force CF_BAI_subskills_terrain_range = 30.0298;

// CF_BAI_boost
force CF_BAI_boost_bulletsToMaxBoost = 5;
force CF_BAI_boost_disableBoost = false;
force CF_BAI_boost_maxBoost = 1.1;
force CF_BAI_boost_minimumShotDistance = 300;
force CF_BAI_boost_minimumShotInterval = 2;
force CF_BAI_boost_targetChangeSleepTime = 0.1;
force CF_BAI_boost_toleranceRange = 50;

// CF_BAI_death
force CF_BAI_death_deathMessageDelay = 10;
force CF_BAI_death_disableDeath = false;
force CF_BAI_death_messageHint = true;
force CF_BAI_death_messageSideChat = true;
force CF_BAI_death_messageSystemChat = false;

// CF_BAI_detect
force CF_BAI_detect_aiplayervision_max_distance = 1500;
force CF_BAI_detect_aivision_aware_chance = 0.9;
force CF_BAI_detect_aivision_aware_knowledge = 1;
force CF_BAI_detect_aivision_careless_chance = 0.5;
force CF_BAI_detect_aivision_careless_knowledge = 0.5;
force CF_BAI_detect_aivision_combat_chance = 1;
force CF_BAI_detect_aivision_combat_knowledge = 1;
force CF_BAI_detect_aivision_nobino_chance = 0.75;
force CF_BAI_detect_aivision_nobino_knowledge = 0.75;
force CF_BAI_detect_aivision_nooptics_chance = 0.65;
force CF_BAI_detect_aivision_nooptics_knowledge = 0.5;
force CF_BAI_detect_aivision_nooptics_range = 400;
force CF_BAI_detect_aivision_nvg_percentage = 0.25;
force CF_BAI_detect_aivision_optics_range = 1500;
force CF_BAI_detect_aivision_safe_chance = 0.8;
force CF_BAI_detect_aivision_safe_knowledge = 1;
force CF_BAI_detect_aivision_stealth_chance = 0.75;
force CF_BAI_detect_aivision_stealth_knowledge = 0.75;
force CF_BAI_detect_disableDetect = false;
force CF_BAI_detect_environmentConiditions_fog = 0.9;
force CF_BAI_detect_environmentConiditions_nightTime = 0.5;
force CF_BAI_detect_environmentConiditions_rain = 0.2;
force CF_BAI_detect_overall_visibility_multiplier = 1.29416;
force CF_BAI_detect_playerVisibility_crouch_chance = 0.5;
force CF_BAI_detect_playerVisibility_crouch_knowledge = 1;
force CF_BAI_detect_playerVisibility_movement = 0.5;
force CF_BAI_detect_playerVisibility_movement_knowledge = 1;
force CF_BAI_detect_playerVisibility_prone_chance = 0.1;
force CF_BAI_detect_playerVisibility_prone_knowledge = 1;
force CF_BAI_detect_playerVisibility_standing_chance = 1;
force CF_BAI_detect_playerVisibility_standing_knowledge = 1;
force CF_BAI_detect_playerVisibility_terrain_count = 4;

// CF_BAI_suppression
force CF_BAI_suppression_aimingAccuracy = 0.2;
force CF_BAI_suppression_aimingShake = 0.2;
force CF_BAI_suppression_aimingSpeed = 0.2;
force CF_BAI_suppression_bulletImpact = 0.1;
force CF_BAI_suppression_commanding = 0.2;
force CF_BAI_suppression_courage = 0.2;
force CF_BAI_suppression_decay = 0.03;
force CF_BAI_suppression_decaySleep = 5;
force CF_BAI_suppression_disableSuppression = false;
force CF_BAI_suppression_general = 0.5;
force CF_BAI_suppression_heldTime = 20;
force CF_BAI_suppression_reloadSpeed = 0.5;
force CF_BAI_suppression_spotDistance = 0.5;
force CF_BAI_suppression_spotTime = 0.5;

// Community Base Addons
cba_diagnostic_ConsoleIndentType = -1;
force cba_diagnostic_watchInfoRefreshRate = 0.2;
cba_disposable_dropUsedLauncher = 2;
force cba_disposable_replaceDisposableLauncher = true;
cba_events_repetitionMode = 1;
force cba_network_loadoutValidation = 0;
cba_optics_usePipOptics = true;
cba_ui_notifyLifetime = 4;
cba_ui_StorePasswords = 1;

// Death and Hit Reactions
force WBK_DeathAnimMod_Death_Chance = "100";
force WBK_DeathAnimMod_Deaths_AI = false;
force WBK_DeathAnimMod_Deaths_HUGEANIMS = true;
force WBK_DeathAnimMod_Deaths_NECKSHOTS = true;
force WBK_DeathAnimMod_Deaths_PLR = false;
force WBK_DeathAnimMod_Flinch_AI = true;
force WBK_DeathAnimMod_Flinch_PLR = true;
force WBK_DeathAnimMod_Hit_AI = true;
force WBK_DeathAnimMod_Hit_Chance = "100";
force WBK_DeathAnimMod_Hit_Chance_PLR = "20";
force WBK_DeathAnimMod_Hit_PLR = true;

// DUI - Squad Radar - Indikatoren
force diwako_dui_indicators_crew_range_enabled = false;
diwako_dui_indicators_fov_scale = false;
diwako_dui_indicators_icon_buddy = true;
diwako_dui_indicators_icon_leader = true;
diwako_dui_indicators_icon_medic = true;
diwako_dui_indicators_range = 20;
diwako_dui_indicators_range_crew = 300;
diwako_dui_indicators_range_scale = false;
force diwako_dui_indicators_rangeLimit = 100;
diwako_dui_indicators_show = true;
diwako_dui_indicators_size = 1;
diwako_dui_indicators_style = "standard";
diwako_dui_indicators_useACENametagsRange = true;

// DUI - Squad Radar - Line Compass
diwako_dui_linecompass_ACEFingeringColor = [1,0.66,0,1];
diwako_dui_linecompass_CompassAvailableShown = true;
diwako_dui_linecompass_compassRange = 35;
force diwako_dui_linecompass_compassRangeLimit = 50;
diwako_dui_linecompass_CustomWaypointColor = [0,0,0.87,1];
diwako_dui_linecompass_DefaultIconColor = [0.5,0.87,0.5,1];
diwako_dui_linecompass_DrawBearing = 2;
diwako_dui_linecompass_Enabled = true;
diwako_dui_linecompass_enableOcclusion = false;
diwako_dui_linecompass_IconOutline = 0;
diwako_dui_linecompass_occlusionFadeSpeed = 3.5;
diwako_dui_linecompass_showSpeaking = true;
diwako_dui_linecompass_SwapOrder = true;
diwako_dui_linecompass_WaypointColor = [0,0,0.87,1];

// DUI - Squad Radar - Main
diwako_dui_ace_hide_interaction = true;
diwako_dui_colors = "standard";
diwako_dui_font = "RobotoCondensed";
diwako_dui_icon_style = "standard";
diwako_dui_main_hide_dialog = true;
diwako_dui_main_hide_ui_by_default = false;
diwako_dui_main_squadBlue = [0,0,1,1];
diwako_dui_main_squadGreen = [0,1,0,1];
diwako_dui_main_squadMain = [1,1,1,1];
diwako_dui_main_squadRed = [1,0,0,1];
diwako_dui_main_squadYellow = [1,1,0,1];
diwako_dui_main_trackingColor = [0.93,0.26,0.93,1];
diwako_dui_reset_ui_pos = false;

// DUI - Squad Radar - Namensschilder
diwako_dui_nametags_customRankStyle = "[[""PRIVATE"",""CORPORAL"",""SERGEANT"",""LIEUTENANT"",""CAPTAIN"",""MAJOR"",""COLONEL""],[""Pvt."",""Cpl."",""Sgt."",""Lt."",""Capt."",""Maj."",""Col.""]]";
diwako_dui_nametags_deadColor = [0.2,0.2,0.2,1];
diwako_dui_nametags_deadRenderDistance = 3.5;
diwako_dui_nametags_drawRank = true;
diwako_dui_nametags_enabled = true;
diwako_dui_nametags_enableFOVBoost = true;
diwako_dui_nametags_enableOcclusion = true;
diwako_dui_nametags_fadeInTime = 0.05;
diwako_dui_nametags_fadeOutTime = 0.5;
diwako_dui_nametags_fontGroup = "RobotoCondensedLight";
diwako_dui_nametags_fontGroupNameSize = 8;
diwako_dui_nametags_fontName = "RobotoCondensedBold";
diwako_dui_nametags_fontNameSize = 10;
diwako_dui_nametags_groupColor = [1,1,1,1];
diwako_dui_nametags_groupFontShadow = 1;
diwako_dui_nametags_groupNameOtherGroupColor = [0.6,0.85,0.6,1];
diwako_dui_nametags_nameFontShadow = 1;
diwako_dui_nametags_nameOtherGroupColor = [0.2,1,0,1];
diwako_dui_nametags_rankNameStyle = "default";
diwako_dui_nametags_renderDistance = 40;
diwako_dui_nametags_showUnconAsDead = true;
diwako_dui_nametags_useLIS = true;
diwako_dui_nametags_useSideIsFriendly = true;

// DUI - Squad Radar - Radar
diwako_dui_compass_hide_alone_group = false;
diwako_dui_compass_hide_blip_alone_group = false;
diwako_dui_compass_icon_scale = 1;
diwako_dui_compass_opacity = 1;
diwako_dui_compass_style = ["\z\diwako_dui\addons\radar\UI\compass_styles\olde\limited.paa","\z\diwako_dui\addons\radar\UI\compass_styles\olde\full.paa"];
diwako_dui_compassRange = 35;
diwako_dui_compassRefreshrate = 0.5;
diwako_dui_dir_showMildot = false;
diwako_dui_dir_size = 1.25;
diwako_dui_distanceWarning = 3;
diwako_dui_enable_compass = true;
diwako_dui_enable_compass_dir = 2;
diwako_dui_enable_occlusion = false;
diwako_dui_enable_occlusion_cone = 360;
diwako_dui_hudScaling = 1;
diwako_dui_namelist = true;
diwako_dui_namelist_bg = 0;
diwako_dui_namelist_only_buddy_icon = false;
diwako_dui_namelist_size = 1;
diwako_dui_namelist_text_shadow = 2;
diwako_dui_namelist_width = 215;
diwako_dui_radar_ace_finger = true;
force diwako_dui_radar_ace_medic = true;
diwako_dui_radar_always_show_unit_numbers = false;
diwako_dui_radar_compassRangeCrew = 500;
force diwako_dui_radar_compassRangeLimit = 50;
diwako_dui_radar_dir_padding = 25;
diwako_dui_radar_dir_shadow = 2;
diwako_dui_radar_enable_seat_icons = 2;
diwako_dui_radar_group_by_vehicle = true;
diwako_dui_radar_icon_opacity = 1;
diwako_dui_radar_icon_opacity_no_player = true;
force diwako_dui_radar_icon_priority_setting = 1;
diwako_dui_radar_icon_scale_crew = 6;
diwako_dui_radar_leadingZeroes = true;
diwako_dui_radar_namelist_hideWhenLeader = false;
diwako_dui_radar_namelist_vertical_spacing = 1;
diwako_dui_radar_occlusion_fade_in_time = 1;
diwako_dui_radar_occlusion_fade_time = 10;
diwako_dui_radar_pointer_color = [1,0.5,0,1];
diwako_dui_radar_pointer_style = "standard";
diwako_dui_radar_show_cardinal_points = true;
diwako_dui_radar_showSpeaking = true;
diwako_dui_radar_showSpeaking_radioOnly = false;
diwako_dui_radar_showSpeaking_replaceIcon = true;
force diwako_dui_radar_sortType = "none";
force diwako_dui_radar_sqlFirst = false;
force diwako_dui_radar_syncGroup = false;
force diwako_dui_radar_vehicleCompassEnabled = false;
diwako_dui_use_layout_editor = false;

// Enhanced Movement Rework
force emr_main_allowClimbOnStandingUnits = false;
force emr_main_allowMidairClimbing = true;
force emr_main_animSpeedCoef = 1;
force emr_main_animSpeedStaminaCoef = 0.4;
force emr_main_assistDuty = 1.5;
force emr_main_assistHeight = 1;
force emr_main_blacklistStr = "";
force emr_main_climbingEnabled = true;
force emr_main_climbOnDuty = 3.4;
force emr_main_climbOverDuty = 3;
force emr_main_dropDuty = 0.7;
emr_main_dropViewElevation = -0.7;
emr_main_enableWalkableSurface = true;
force emr_main_enableWeightCheck = false;
emr_main_hintType = 2;
emr_main_interactBehaviorInVehicle = "DISMOUNT";
force emr_main_jumpDuty = 1;
force emr_main_jumpForwardVelocity = 1.2;
force emr_main_jumpingEnabled = true;
force emr_main_jumpingLoadCoefficient = 1;
force emr_main_jumpVelocity = 3.5;
force emr_main_maxClimbHeight = 2.6;
force emr_main_maxDropHeight = 6;
force emr_main_maxWeightClimb1 = 100;
force emr_main_maxWeightClimb2 = 85;
force emr_main_maxWeightClimb3 = 60;
force emr_main_maxWeightJump = 100;
force emr_main_minClimbTerrain = 0.3;
emr_main_preventHighVaulting = false;
force emr_main_staminaCoefficient = 1;
force emr_main_whitelistStr = "";
force emr_main_yeetCoefficient = 1.4;

// GRAD Trenches
force grad_trenches_functions_allowBigEnvelope = true;
force grad_trenches_functions_allowCamouflage = true;
force grad_trenches_functions_allowDigging = true;
force grad_trenches_functions_allowEffects = true;
force grad_trenches_functions_allowGiantEnvelope = true;
force grad_trenches_functions_allowHitDecay = true;
force grad_trenches_functions_allowLongEnvelope = true;
force grad_trenches_functions_allowShortEnvelope = true;
force grad_trenches_functions_allowSmallEnvelope = true;
force grad_trenches_functions_allowTextureLock = true;
force grad_trenches_functions_allowTrenchDecay = false;
force grad_trenches_functions_allowVehicleEnvelope = true;
force grad_trenches_functions_bigEnvelopeDamageMultiplier = 2;
force grad_trenches_functions_bigEnvelopeDigTime = 40;
force grad_trenches_functions_bigEnvelopeRemovalTime = -1;
force grad_trenches_functions_buildFatigueFactor = 1;
force grad_trenches_functions_camouflageRequireEntrenchmentTool = true;
force grad_trenches_functions_createTrenchMarker = false;
force grad_trenches_functions_decayTime = 1800;
force grad_trenches_functions_giantEnvelopeDamageMultiplier = 1;
force grad_trenches_functions_giantEnvelopeDigTime = 90;
force grad_trenches_functions_giantEnvelopeRemovalTime = -1;
force grad_trenches_functions_hitDecayMultiplier = 1;
force grad_trenches_functions_LongEnvelopeDigTime = 100;
force grad_trenches_functions_LongEnvelopeRemovalTime = -1;
force grad_trenches_functions_playersInAreaRadius = 0;
force grad_trenches_functions_shortEnvelopeDamageMultiplier = 2;
force grad_trenches_functions_shortEnvelopeDigTime = 15;
force grad_trenches_functions_shortEnvelopeRemovalTime = -1;
force grad_trenches_functions_smallEnvelopeDamageMultiplier = 3;
force grad_trenches_functions_smallEnvelopeDigTime = 30;
force grad_trenches_functions_smallEnvelopeRemovalTime = -1;
force grad_trenches_functions_stopBuildingAtFatigueMax = true;
force grad_trenches_functions_textureLockDistance = 5;
force grad_trenches_functions_timeoutToDecay = 7200;
force grad_trenches_functions_vehicleEnvelopeDamageMultiplier = 1;
force grad_trenches_functions_vehicleEnvelopeDigTime = 120;
force grad_trenches_functions_vehicleEnvelopeRemovalTime = -1;
force grad_trenches_functions_vehicleTrenchBuildSpeed = 5;

// KAT - ADV Medical: Airway
force kat_airway_Accuvac_time = 8;
force kat_airway_autoTriage = true;
force kat_airway_block_headTurning_ifAirwayItem = true;
force kat_airway_CancelRecoveryPosition_Time = 3;
force kat_airway_CheckAirway_time = 2;
force kat_airway_checkbox_puking_sound = true;
force kat_airway_enable = true;
force kat_airway_Guedeltubus_time = 6;
force kat_airway_HeadTurn_Interval = 3;
force kat_airway_Hyperextend_Time = 3;
force kat_airway_Larynxtubus_time = 3;
force kat_airway_medLvl_Accuvac = 1;
force kat_airway_medLvl_Guedeltubus = 0;
force kat_airway_medLvl_Larynxtubus = 1;
force kat_airway_medLvl_Suction = 0;
force kat_airway_occlusion_cooldownPeriod = 6;
force kat_airway_occlusion_repeatTimer = 60;
force kat_airway_probability_headturning = 50;
force kat_airway_probability_obstruction = 15;
force kat_airway_probability_occluded = 10;
force kat_airway_RecoveryPosition_Time = 6;
force kat_airway_RecoveryPosition_TimeToDrain = 10;
force kat_airway_ReusableAirwayItems = false;
force kat_airway_string_exit = "";
force kat_airway_Suction_reuse = false;
force kat_airway_Suction_time = 12;

// KAT - ADV Medical: Breathing
force kat_breathing_advPtxChance = 5;
force kat_breathing_advPtxEnable = true;
force kat_breathing_arrestPneumothorax_interval = 30;
force kat_breathing_availOxyHelmet = "'H_PilotHelmetFighter_B', 'H_PilotHelmetFighter_O', 'H_PilotHelmetFighter_I', 'H_PilotHelmetFighter_I_E'";
force kat_breathing_availOxyMask = "'kat_mask_solr'";
force kat_breathing_BVMOxygen_Multiplier = 1;
force kat_breathing_clearChestSealAfterTreatment = true;
force kat_breathing_deepPenetratingInjuryChance = 30;
force kat_breathing_deterioratingPneumothorax_chance = 50;
force kat_breathing_deterioratingPneumothorax_interval = 60;
force kat_breathing_enable = true;
force kat_breathing_enable_selfChestseal = 1;
force kat_breathing_enableCheckBreathing = true;
force kat_breathing_Etco2_Enabled = true;
force kat_breathing_Etco2_Units = 0;
force kat_breathing_HPTXBleedAmount = 0.06;
force kat_breathing_hptxChance = 5;
force kat_breathing_inspectChest_enable = 2;
force kat_breathing_inspectChest_medLvl = 0;
force kat_breathing_inspectChest_time = 6;
force kat_breathing_locationProvideOxygen = 3;
force kat_breathing_medLvl_BVM = 0;
force kat_breathing_medLvl_BVM_Oxygen = 1;
force kat_breathing_medLvl_Chestseal = 0;
force kat_breathing_medLvl_hemopneumothoraxTreatment = 0;
force kat_breathing_medLvl_NasalCannula = 0;
force kat_breathing_medLvl_PocketBVM = 0;
force kat_breathing_medLvl_Pulseoximeter = 1;
force kat_breathing_mildValue = 75;
force kat_breathing_NasalCannula_time = 3;
force kat_breathing_paco2Active = false;
force kat_breathing_PneumothoraxAlwaysVisible = false;
force kat_breathing_PneumothoraxArrest = false;
force kat_breathing_pneumothoraxChance = 5;
force kat_breathing_pneumothoraxDamageThreshold = 0.4;
force kat_breathing_pneumothoraxDamageThreshold_TakenDamage = true;
force kat_breathing_PortableOxygenTank_RefillTime = 5;
force kat_breathing_PulseOximeter_SpO2Warning = 85;
force kat_breathing_severeValue = 66;
force kat_breathing_showCyanosis = true;
force kat_breathing_showPneumothorax_dupe = false;
force kat_breathing_slightValue = 90;
force kat_breathing_SpO2_cardiacActive = true;
force kat_breathing_SpO2_cardiacValue = 55.0964;
force kat_breathing_SpO2_dieActive = true;
force kat_breathing_SpO2_dieValue = 40.3822;
force kat_breathing_SpO2_MultiplyNegative = 1;
force kat_breathing_SpO2_MultiplyPositive = 1;
force kat_breathing_SpO2_perfusion = true;
force kat_breathing_SpO2_PerfusionMultiplier = 1;
force kat_breathing_SpO2_unconscious = 70.1618;
force kat_breathing_Stable_spo2 = 85.055;
force kat_breathing_staminaLossAtLowSPO2 = true;
force kat_breathing_stethoscopeListeningTime = 15;
kat_breathing_stethoscopeSoundVolume = 2;
force kat_breathing_TensionHemothoraxAlwaysVisible = false;

// KAT - ADV Medical: Chemical
force kat_chemical_availGasmask = "'G_AirPurifyingRespirator_01_F', 'kat_mask_M50', 'kat_mask_M04'";
force kat_chemical_gasmask_durability = 900;
kat_chemical_gasMaskSoundVolume = 1;
force kat_chemical_infectionTime = 60;
force kat_chemical_maskStaminaLoss = false;
force kat_chemical_showPoisoning = true;
force kat_chemical_tearGasDropChance = 0;

// KAT - ADV Medical: Circulation
force kat_circulation_abgEnable = false;
force kat_circulation_AdvRhythm = true;
force kat_circulation_AdvRhythm_AED_ROSC_Chance = 50;
force kat_circulation_AdvRhythm_asystoleBloodlossThreshold = 3.6;
force kat_circulation_AdvRhythm_canDeteriorate = true;
force kat_circulation_AdvRhythm_CPR_ROSC_Chance = 5;
force kat_circulation_AdvRhythm_deteriorateAfterTreatment = true;
force kat_circulation_AdvRhythm_deteriorateTimeMax = 900;
force kat_circulation_AdvRhythm_deteriorateTimeWeight = 180;
force kat_circulation_AdvRhythm_Hardcore_Enable = false;
force kat_circulation_AdvRhythm_hardcoreDeteriorationChance = 10;
force kat_circulation_AdvRhythm_HTHold = false;
force kat_circulation_AdvRhythm_PEAChance = 50;
force kat_circulation_AdvRhythm_VTChance = 50;
force kat_circulation_AED_duringCpr = true;
force kat_circulation_AED_MaxChance = 80;
force kat_circulation_AED_MinChance = 45;
force kat_circulation_AED_X_MaxChance = 90;
force kat_circulation_AED_X_MinChance = 50;
force kat_circulation_AED_X_Monitor_SpO2Warning = 85;
force kat_circulation_AED_X_VitalsMonitor_BloodPressureInterval = 0;
force kat_circulation_AED_X_VitalsMonitor_BloodPressureInterval_Time = 30;
force kat_circulation_AED_X_VitalsMonitor_SoundsSelect = 1;
force kat_circulation_AEDX_VitalsMonitor_AttachTime = 6;
force kat_circulation_AEDX_VitalsMonitor_DetachTime = 3;
force kat_circulation_blood_draw_limit = 3.6;
force kat_circulation_blood_drawTime_250ml = 25;
force kat_circulation_blood_drawTime_500ml = 50;
force kat_circulation_bloodGroups = true;
force kat_circulation_bloodTypeCustomList = "O,O,A,A,O_N,B,A_N,AB,B_N,AB_N";
force kat_circulation_bloodTypeRandomWeighted = true;
force kat_circulation_bloodTypeSetting = 4;
kat_circulation_bloodTypeSettingPlayer = "O_N";
force kat_circulation_cardiacArrestBleedRate = 0.05;
force kat_circulation_CPR_ChanceInterval = 15;
force kat_circulation_CPR_MaxChance_Default = 20;
force kat_circulation_CPR_MaxChance_Doctor = 40;
force kat_circulation_CPR_MaxChance_RegularMedic = 30;
force kat_circulation_CPR_MinChance_Default = 10;
force kat_circulation_CPR_MinChance_Doctor = 20;
force kat_circulation_CPR_MinChance_RegularMedic = 15;
force kat_circulation_CPR_OxygenationPeriod = 15;
force kat_circulation_Defibrillator_DistanceLimit = 6;
force kat_circulation_DefibrillatorPads_AttachTime = 6;
force kat_circulation_DefibrillatorPads_DetachTime = 3;
force kat_circulation_deterioratingTamponade_chance = 35;
force kat_circulation_deterioratingTamponade_interval = 60;
force kat_circulation_enable = true;
force kat_circulation_enable_CPR_Chances = true;
force kat_circulation_enable_selfBloodDraw = 1;
force kat_circulation_hardcoreDiagnose = false;
force kat_circulation_medLvl_AED = 0;
force kat_circulation_medLvl_AED_Station_Interact = 0;
force kat_circulation_medLvl_AED_X = 1;
force kat_circulation_medLvl_BPCuff = 0;
force kat_circulation_medLvl_StethHR = 0;
force kat_circulation_tamponadeChance = 10;
force kat_circulation_treatmentTime_BPCuff = 12;
force kat_circulation_treatmentTime_StethHR = 8;
force kat_circulation_useLocation_AED = 0;

// KAT - ADV Medical: Feedback
force kat_feedback_effectLowSpO2 = 90;
force kat_feedback_enableOpioidEffect = true;

// KAT - ADV Medical: GUI
force kat_gui_ColoredLogs = true;
kat_gui_showPatientSideLabels = false;

// KAT - ADV Medical: Hypothermia
force kat_hypothermia_hypothermiaActive = true;

// KAT - ADV Medical: Misc
kat_misc_AFAK_Container = 0;
kat_misc_AFAK_Item_Color = [0.67,0.84,0.9];
force kat_misc_AFAK_RemoveWhenEmpty = true;
kat_misc_AFAK_Slot_Color = [1,0.96,0.32];
force kat_misc_AFAKFifthSlotItem = "[['kat_guedel', 4]]";
force kat_misc_AFAKFirstSlotItem = "[['ACE_tourniquet', 4], ['ACE_splint', 2]]";
force kat_misc_AFAKFourthSlotItem = "[['kat_chestSeal', 3], ['kat_ncdKit', 3]]";
force kat_misc_AFAKSecondSlotItem = "[['ACE_packingBandage', 10], ['ACE_quikclot', 10]]";
force kat_misc_AFAKSixthSlotItem = "[['ACE_epinephrine', 3], ['kat_Carbonate', 1]]";
force kat_misc_AFAKThirdSlotItem = "[['ACE_morphine', 3], ['kat_Penthrox', 1], ['kat_Painkiller', 1]]";
force kat_misc_allowSharedVehicleEquipment = 4;
kat_misc_armbandSlingLeftArm = "[0.2, -0.39, -0.2]";
kat_misc_armbandSlingLeftArmRotation = "[240, 33, 26]";
kat_misc_armbandSlingLeftLeg = "[0.435, -0.075, -0.38]";
kat_misc_armbandSlingLeftLegRotation = "[-160, -5, 45]";
kat_misc_armbandSlingRightArm = "[-0.228, -0.1, -0.43]";
kat_misc_armbandSlingRightArmRotation = "[5, -5, -5]";
kat_misc_armbandSlingRightLeg = "[-0.32, -0.29, -0.42]";
kat_misc_armbandSlingRightLegRotation = "[-30, -5, 38]";
force kat_misc_enable = true;
force kat_misc_enableStitchFullBody = false;
kat_misc_IFAK_Container = 0;
kat_misc_IFAK_Item_Color = [0.67,0.84,0.9];
force kat_misc_IFAK_RemoveWhenEmpty = true;
kat_misc_IFAK_Slot_Color = [1,0.3,0.3];
force kat_misc_IFAKFirstSlotItem = "[['ACE_tourniquet', 2]]";
force kat_misc_IFAKFourthSlotItem = "[['kat_chestSeal', 1]]";
force kat_misc_IFAKSecondSlotItem = "[['ACE_packingBandage', 5], ['ACE_quikclot', 5]]";
force kat_misc_IFAKThirdSlotItem = "[['kat_Painkiller', 1]]";
force kat_misc_incompatibilityWarning = true;
kat_misc_MFAK_Container = 0;
kat_misc_MFAK_Item_Color = [0.67,0.84,0.9];
force kat_misc_MFAK_RemoveWhenEmpty = true;
kat_misc_MFAK_Slot_Color = [0.56,0.93,0.56];
force kat_misc_MFAKEighthSlotItem = "[['kat_Pulseoximeter', 1], ['kat_pocketBVM', 1], ['kat_AED', 1]]";
force kat_misc_MFAKFifthSlotItem = "[['kat_larynx', 6]]";
force kat_misc_MFAKFirstSlotItem = "[['ACE_tourniquet', 6], ['ACE_splint', 4]]";
force kat_misc_MFAKFourthSlotItem = "[['kat_chestSeal', 6], ['kat_aatKit', 3], ['kat_ncdKit', 3], ['kat_stethoscope', 1]]";
force kat_misc_MFAKSecondSlotItem = "[['ACE_packingBandage', 15], ['ACE_quikclot', 15], ['ACE_fieldDressing', 15]]";
force kat_misc_MFAKSeventhSlotItem = "[['ACE_salineIV_250', 4], ['kat_IV_16', 4]]";
force kat_misc_MFAKSixthSlotItem = "[['ACE_epinephrine', 6], ['kat_IV_16', 4], ['kat_nitroglycerin', 2], ['kat_phenylephrine', 2], ['kat_atropine', 2], ['kat_naloxone', 2], ['kat_Carbonate', 1]]";
force kat_misc_MFAKThirdSlotItem = "[['ACE_morphine', 6], ['kat_Painkiller', 2], ['kat_Penthrox', 2]]";
force kat_misc_tourniquetEffects_Enable = true;
force kat_misc_tourniquetEffects_NegativeMultiplier = 1;
force kat_misc_tourniquetEffects_PositiveMultiplier = 1;
force kat_misc_treatmentTimeDetachTourniquet = 7;

// KAT - ADV Medical: Pharmacy
force kat_pharma_allowStackScript_EACA = true;
force kat_pharma_allowStackScript_TXA = true;
force kat_pharma_bandageCycleTime_EACA = 8;
force kat_pharma_bandageCycleTime_TXA = 5;
force kat_pharma_blockChance = 15;
force kat_pharma_carbonateChance = 100;
force kat_pharma_CheckCoag_Location = 0;
force kat_pharma_CheckCoag_MedLevel = 1;
force kat_pharma_CheckCoag_TreatmentTime = 10;
force kat_pharma_coagulation = true;
force kat_pharma_coagulation_allow_clot_text = true;
force kat_pharma_coagulation_allow_EACA_script = true;
force kat_pharma_coagulation_allow_LargeWounds = true;
force kat_pharma_coagulation_allow_MediumWounds = true;
force kat_pharma_coagulation_allow_MinorWounds = true;
force kat_pharma_coagulation_allow_TXA_script = true;
force kat_pharma_coagulation_allowOnAI = false;
force kat_pharma_coagulation_factor_count = 30;
force kat_pharma_coagulation_factor_limit = 60;
force kat_pharma_coagulation_factor_regenerate_time = 150;
force kat_pharma_coagulation_on_all_Bodyparts = true;
force kat_pharma_coagulation_requireBV = 3.6;
force kat_pharma_coagulation_requireHR = true;
force kat_pharma_coagulation_time = 10;
force kat_pharma_coagulation_time_large = 45;
force kat_pharma_coagulation_time_medium = 30;
force kat_pharma_coagulation_time_minor = 15;
force kat_pharma_coagulation_tourniquetBlock = true;
force kat_pharma_eacaClearTrauma = false;
force kat_pharma_ivCheckLimbDamage = false;
force kat_pharma_IVdrop = 600;
force kat_pharma_IVdropEnable = true;
force kat_pharma_IVflowControl = false;
force kat_pharma_IVreuse = false;
force kat_pharma_keepScriptRunning_EACA = true;
force kat_pharma_keepScriptRunning_TXA = true;
force kat_pharma_kidneyAction = false;
force kat_pharma_MedicationsRequireInsIV = true;
force kat_pharma_medLvl_Amiodarone = 0;
force kat_pharma_medLvl_ApplyIO = 1;
force kat_pharma_medLvl_ApplyIV = 0;
force kat_pharma_medLvl_Atropine = 0;
force kat_pharma_medLvl_Caffeine = 0;
force kat_pharma_medLvl_Carbonate = 1;
force kat_pharma_medLvl_CWMP = 0;
force kat_pharma_medLvl_EACA = 1;
force kat_pharma_medLvl_EpinephrineIV = 1;
force kat_pharma_medLvl_Etomidate = 1;
force kat_pharma_medLvl_Fentanyl = 1;
force kat_pharma_medLvl_Flumezenil = 1;
force kat_pharma_medLvl_Ketamine = 1;
force kat_pharma_medLvl_Lidocaine = 1;
force kat_pharma_medLvl_Lorazepam = 1;
force kat_pharma_medLvl_Nalbuphine = 1;
force kat_pharma_medLvl_Naloxone = 1;
force kat_pharma_medLvl_Nitroglycerin = 1;
force kat_pharma_medLvl_Norepinephrine = 1;
force kat_pharma_medLvl_Penthrox = 0;
force kat_pharma_medLvl_Pervitin = 0;
force kat_pharma_medLvl_Phenylephrine = 1;
force kat_pharma_medLvl_Reorientation = 0;
force kat_pharma_medLvl_TXA = 1;
force kat_pharma_pervitinSpeed = 1.15;
force kat_pharma_Reorientation_Enable = true;
force kat_pharma_Reorientation_Slap = true;
force kat_pharma_reorientationChance = 14.9219;
force kat_pharma_RequireInsIV = true;
force kat_pharma_RequireInsIVBloodDraw = true;
force kat_pharma_staminaMedication = false;
force kat_pharma_treatmentTime_Amiodarone = 7;
force kat_pharma_treatmentTime_ApplyIO = 7;
force kat_pharma_treatmentTime_ApplyIV = 7;
force kat_pharma_treatmentTime_Atropine = 7;
force kat_pharma_treatmentTime_Caffeine = 7;
force kat_pharma_treatmentTime_Carbonate = 7;
force kat_pharma_treatmentTime_CWMP = 7;
force kat_pharma_treatmentTime_EACA = 7;
force kat_pharma_treatmentTime_EpinephrineIV = 7;
force kat_pharma_treatmentTime_Etomidate = 2;
force kat_pharma_treatmentTime_Fentanyl = 7;
force kat_pharma_treatmentTime_Flumazenil = 2;
force kat_pharma_treatmentTime_Ketamine = 7;
force kat_pharma_treatmentTime_Lidocaine = 7;
force kat_pharma_treatmentTime_Lorazepam = 2;
force kat_pharma_treatmentTime_Nalbuphine = 7;
force kat_pharma_treatmentTime_Naloxone = 7;
force kat_pharma_treatmentTime_Nitroglycerin = 7;
force kat_pharma_treatmentTime_Norepinephrine = 7;
force kat_pharma_treatmentTime_Penthrox = 8;
force kat_pharma_treatmentTime_Pervitin = 5;
force kat_pharma_treatmentTime_Phenylephrine = 7;
force kat_pharma_treatmentTime_Reorientation = 2;
force kat_pharma_treatmentTime_TXA = 7;
force kat_pharma_weapon_sway_pervitin = true;

// KAT - ADV Medical: Surgery
force kat_surgery_closedLocation = 0;
force kat_surgery_closedReduction_MedLevel = 2;
force kat_surgery_closedReductionFailChance = 10;
force kat_surgery_closedTime = 10;
force kat_surgery_compoundChance = 30;
force kat_surgery_enable_fracture = true;
force kat_surgery_enable_selfCheckFracture = 1;
force kat_surgery_fractureCheck_MedLevel = 0;
force kat_surgery_fractureCheck_Time = 10;
force kat_surgery_incisionTime = 10;
force kat_surgery_intermediateTime = 8;
force kat_surgery_npwt_MedLevel = 2;
force kat_surgery_npwtLocation = 3;
force kat_surgery_npwtTime = 5;
force kat_surgery_openTime = 15;
force kat_surgery_pericardialtap_MedLevel = 2;
force kat_surgery_pericardialtapLocation = 3;
force kat_surgery_pericardialtapTime = 8;
force kat_surgery_reboa_MedLevel = 2;
force kat_surgery_reboaLocation = 3;
force kat_surgery_reboaTime = 8;
force kat_surgery_simpleChance = 60;
force kat_surgery_Surgery_ConsciousnessRequirement = 0;
force kat_surgery_surgicalAction_MedLevel = 2;
force kat_surgery_surgicalLocation = 3;
force kat_surgery_ultrasound_MedLevel = 2;
force kat_surgery_ultrasoundLocation = 3;
force kat_surgery_ultrasoundTime = 8;

// KAT - ADV Medical: Vitals
force kat_vitals_basicDiagnosticTime = 15;
force kat_vitals_enableBasicDiagnostic = true;
force kat_vitals_enableFluidShift = true;
force kat_vitals_enableSimpleMedical = true;

// KAT - ADV Medical: Watch
force kat_watch_altitudeUnit = 0;
force kat_watch_pressureUnit = 0;
force kat_watch_temperatureUnit = 0;
force kat_watch_watchInaccuracy = false;

// Laxemann Immerse
force L_Immerse_exShake = true;
force L_Immerse_force = false;
force L_Immerse_recoil = true;
force L_Immerse_twitch = true;

// NIArms
force niarms_gripSwitch = true;
force niarms_magSwitch = true;

// RR Immersive Maps
RR_mapStuff_enableCompassAnimations = true;
RR_mapStuff_enableMapAnimations = true;
RR_mapStuff_enableMapInteractions = true;

// Simplex Support Services
force SSS_setting_adminFullAccess = true;
SSS_setting_adminLimitSide = false;
force SSS_setting_cleanupCrew = true;
force SSS_setting_deleteVehicleOnEntityRemoval = false;
force SSS_setting_directActionRequirement = false;
force SSS_setting_GiveUAVTerminal = true;
force SSS_setting_milsimModeArtillery = false;
force SSS_setting_milsimModeCAS = false;
force SSS_setting_milsimModeLogistics = false;
force SSS_setting_milsimModeTransport = false;
force SSS_setting_removeSupportOnVehicleDeletion = true;
force SSS_setting_resetVehicleOnRTB = true;
force SSS_setting_restoreCrewOnRTB = true;
force SSS_setting_slingLoadSearchRadius = 100;
force SSS_setting_slingLoadWhitelist = "";
SSS_setting_useChatNotifications = false;

// SNC Anti-Bounce System
force ABS_enableMod = true;

// SNC Groupmanager
force SNC_dynamic_Group_dynamicGroupTracker = false;
force SNC_dynamic_Group_EnableMapTracker = true;
force SNC_dynamic_Group_indicateGroupsize = false;
force SNC_dynamic_Group_Interval = 1;
force SNC_dynamic_Group_SNC_GroupFaction = "['US Army','BW']";
force SNC_dynamic_Group_SNC_GroupLanguage = "['DE','EN']";
force SNC_dynamic_Group_startMarkerName = "";
force SNC_dynamic_Group_staticGroupList = true;

// SNC Marker
SNC_dynamic_Group_SNC_MapMarker = false;
force SNC_dynamic_Group_SNC_MapMarker_Whitelist = "['76561198100256441']";

// STX Civilians
force stx_civilians_aircraftAltitude = 600;
force stx_civilians_aircraftChance = 0.5;
force stx_civilians_aircraftClassesStr = "[""C_Heli_Light_01_civil_F"",1,""C_Plane_Civil_01_F"",1,""B_Plane_CAS_01_Cluster_F"",1,""B_Plane_Fighter_01_Cluster_F"",1]";
force stx_civilians_aircraftMaxTime = 480;
force stx_civilians_aircraftMinTime = 180;
force stx_civilians_aircraftSpawnDistance = 3000;
force stx_civilians_aircraftTTL = 300;
force stx_civilians_autoStart = false;
force stx_civilians_autoStartAircraft = false;
force stx_civilians_cachingDefault = false;
force stx_civilians_cachingDistance = 2000;
force stx_civilians_cachingEnabled = true;
force stx_civilians_driverCount = 3;
force stx_civilians_driverSpawnDelay = 0.3;
force stx_civilians_driverSpawnRadius = 550;
force stx_civilians_goAwayAction = true;
force stx_civilians_minPanicTime = 120;
force stx_civilians_parkedCount = 5;
force stx_civilians_parkedSpawnDelay = 0.35;
force stx_civilians_parkedSpawnRadius = 500;
force stx_civilians_pedestrianCount = 6;
force stx_civilians_pedSpawnDelay = 0.2;
force stx_civilians_pedSpawnRadius = 450;
force stx_civilians_unitClassesStr = "[""C_Man_casual_2_F"",""C_Man_casual_3_F"",""C_man_w_worker_F"",""C_man_polo_2_F"",""C_Man_casual_1_F"",""C_man_polo_4_F""]";
force stx_civilians_useAgents = true;
force stx_civilians_vehClassesStr = "[""C_Truck_02_fuel_F"",""C_Truck_02_box_F"",""C_Truck_02_covered_F"",""C_Offroad_01_repair_F"",""C_Van_01_box_F"",""C_Offroad_01_F"",""C_Offroad_01_covered_F"",""C_SUV_01_F""]";

// STX Common
force stx_common_applySubSkills = false;
force stx_common_arsenalAnimEnabled = false;
force stx_common_arsenalBlacklistStr = "";
force stx_common_arsenalDummyEnabled = false;
force stx_common_arsenalWhitelistStr = "";
stx_common_hintType = 2;
force stx_common_skillAimingAccuracy = 0.5;
force stx_common_skillAimingShake = 0.5;
force stx_common_skillAimingSpeed = 0.5;
force stx_common_skillCommanding = 0.5;
force stx_common_skillCourage = 0.5;
force stx_common_skillGeneral = 0.5;
force stx_common_skillReloadSpeed = 0.5;
force stx_common_skillSpotDistance = 0.5;
force stx_common_skillSpotTime = 0.5;
force stx_common_slingloadMassOverride = true;
force stx_optionautoParachute = true;

// STX Extras
force stx_extras_parachuteClass = "B_Parachute";
force stx_extras_virtualDriverAllow = true;
force stx_extras_virtualDriverClone = false;
force stx_extras_virtualDriverRemoveOnExit = true;

// STX Logistics
force stx_logistics_boxSpawnerClassesStr = "Box_NATO_Equip_F,B_supplyCrate_F,Box_NATO_Ammo_F,Box_NATO_Support_F,Box_NATO_Wps_F";
force stx_logistics_canteenCapacity = 4;
force stx_logistics_deployableResupplyClass = "Box_NATO_Ammo_F";
force stx_logistics_deployableResupplyCooldown = "0";
force stx_logistics_deployableResupplyExpiration = "300";
force stx_logistics_enableCanteen = false;
force stx_logistics_enableFuelConsumption = false;
stx_logistics_flashingFrequency = 0.4;
force stx_logistics_maxFuelConsumption = 40;
force stx_logistics_medicalClassesStr = "[""FirstAidKit"",""Medikit"",""ACE_fieldDressing"",""ACE_packingBandage"",""ACE_elasticBandage"",""ACE_tourniquet"",""ACE_splint"",""ACE_morphine"",""ACE_adenosine"",""ACE_epinephrine"",""ACE_plasmaIV"",""ACE_plasmaIV_500"",""ACE_plasmaIV_250"",""ACE_bloodIV"",""ACE_bloodIV_500"",""ACE_bloodIV_250"",""ACE_salineIV"",""ACE_salineIV_500"",""ACE_salineIV_250"",""ACE_quikclot"",""ACE_personalAidKit"",""ACE_surgicalKit"",""ACE_bodyBag""]";
force stx_logistics_medicalDefaultsStr = "[""ACE_fieldDressing"",""ACE_packingBandage"",""ACE_elasticBandage"",""ACE_tourniquet"",""ACE_splint"",""ACE_morphine"",""ACE_adenosine"",""ACE_epinephrine"",""ACE_bloodIV"",""ACE_bloodIV_500"",""ACE_bloodIV_250"",""ACE_surgicalKit"",""ACE_bodyBag""]";
force stx_logistics_minFuelConsumption = 180;
force stx_logistics_nudgeSizeCoef = 0.3;
stx_logistics_visualAid = 3;

// STX Main
stx_optiondebug = false;

// STX Military
force stx_military_AssistCoef = 1.4;
force stx_military_cachingDefault = false;
force stx_military_cachingDistance = 3500;
force stx_military_cachingEnabled = false;
stx_military_debug = false;
force stx_military_flaresChance = 0.3;
force stx_military_flaresEnabled = true;
force stx_military_QRFRatio = 0.7;
force stx_military_RatingCar = 3;
force stx_military_RatingHelicopter = 7;
force stx_military_RatingInfantry = 1;
force stx_military_RatingTank = 6;
force stx_military_smokeChance = 0.5;
force stx_military_smokeColorEAST = 0;
force stx_military_smokeColorGUER = 0;
force stx_military_smokeColorWEST = 0;
force stx_military_smokeEnabled = true;

// STX Reserve
force stx_reserve_loadDistance = 3500;
force stx_reserve_saveDistance = 4000;

// Zeus Enhanced
force zen_area_markers_editableMarkers = 0;
force zen_building_markers_enabled = false;
force zen_camera_adaptiveSpeed = true;
force zen_camera_defaultSpeedCoef = 1;
force zen_camera_fastSpeedCoef = 1;
force zen_camera_followTerrain = true;
force zen_common_ascensionMessages = false;
force zen_common_autoAddObjects = true;
force zen_common_cameraBird = false;
force zen_common_darkMode = false;
force zen_common_disableGearAnim = true;
force zen_common_preferredArsenal = 1;
force zen_compat_ace_hideModules = false;
force zen_context_menu_enabled = 2;
force zen_context_menu_overrideWaypoints = false;
force zen_editor_addGroupIcons = false;
force zen_editor_addModIcons = false;
force zen_editor_declutterEmptyTree = false;
force zen_editor_disableLiveSearch = false;
force zen_editor_moveDisplayToEdge = true;
force zen_editor_parachuteSounds = true;
zen_editor_previews_enabled = true;
force zen_editor_randomizeCopyPaste = false;
force zen_editor_removeWatermark = true;
force zen_editor_unitRadioMessages = 0;
force zen_placement_enabled = false;
force zen_remote_control_cameraExitPosition = 2;
force zen_visibility_enabled = 1;
force zen_visibility_maxDistance = 100;
zen_vision_enableBlackHot = false;
zen_vision_enableBlackHotGreenCold = false;
zen_vision_enableBlackHotRedCold = false;
zen_vision_enableGreenHotCold = false;
zen_vision_enableNVG = true;
zen_vision_enableRedGreenThermal = false;
zen_vision_enableRedHotCold = false;
zen_vision_enableWhiteHot = true;
zen_vision_enableWhiteHotRedCold = false;

// Zeus Enhanced - Attribute
zen_attributes_enableAbilities = true;
zen_attributes_enableAmmo = true;
zen_attributes_enableAmmoCargo = true;
zen_attributes_enableArsenal = true;
zen_attributes_enableBuildingMarker = true;
zen_attributes_enableDamage = true;
zen_attributes_enableEngine = true;
zen_attributes_enableExecute = true;
zen_attributes_enableFuel = true;
zen_attributes_enableFuelCargo = true;
zen_attributes_enableGarage = true;
zen_attributes_enableGroupBehaviour = true;
zen_attributes_enableGroupCombatMode = true;
zen_attributes_enableGroupExecute = true;
zen_attributes_enableGroupFormation = true;
zen_attributes_enableGroupID = true;
zen_attributes_enableGroupSide = true;
zen_attributes_enableGroupSkill = true;
zen_attributes_enableGroupSpeed = true;
zen_attributes_enableGroupStance = true;
zen_attributes_enableHealth = true;
zen_attributes_enableInventory = true;
zen_attributes_enableLights = true;
zen_attributes_enableMarkerAlpha = true;
zen_attributes_enableMarkerColor = true;
zen_attributes_enableMarkerText = true;
zen_attributes_enableName = true;
zen_attributes_enablePlateNumber = true;
zen_attributes_enableRank = true;
zen_attributes_enableRepairCargo = true;
zen_attributes_enableRespawnPosition = true;
zen_attributes_enableRespawnVehicle = true;
zen_attributes_enableSensors = true;
zen_attributes_enableSkill = true;
zen_attributes_enableSkills = true;
zen_attributes_enableStance = true;
zen_attributes_enableStates = true;
zen_attributes_enableTraits = true;
zen_attributes_enableVehicleLock = true;
zen_attributes_enableWaypointBehaviour = true;
zen_attributes_enableWaypointCombatMode = true;
zen_attributes_enableWaypointFormation = true;
zen_attributes_enableWaypointLoiterAltitude = true;
zen_attributes_enableWaypointLoiterDirection = true;
zen_attributes_enableWaypointLoiterRadius = true;
zen_attributes_enableWaypointSpeed = true;
zen_attributes_enableWaypointTimeout = true;
zen_attributes_enableWaypointType = true;

// Zeus Enhanced - Fraktionsfilter
force zen_faction_filter_0_DSF_CHECH = true;
force zen_faction_filter_0_DSF_HAMAS = true;
force zen_faction_filter_0_DSF_HEZB = true;
force zen_faction_filter_0_DSF_IGF = true;
force zen_faction_filter_0_DSF_IGF_groups = true;
force zen_faction_filter_0_DSF_IRAN = true;
force zen_faction_filter_0_DSF_LDPR = true;
force zen_faction_filter_0_DSF_PMF = true;
force zen_faction_filter_0_DSF_SAA = true;
force zen_faction_filter_0_DSF_TAL = true;
force zen_faction_filter_0_DSF_WAG = true;
force zen_faction_filter_0_OPF_F = true;
force zen_faction_filter_0_OPF_G_F = true;
force zen_faction_filter_0_OPF_GEN_F = true;
force zen_faction_filter_0_OPF_R_F = true;
force zen_faction_filter_0_OPF_T_F = true;
force zen_faction_filter_0_rhs_faction_msv = true;
force zen_faction_filter_0_rhs_faction_rva = true;
force zen_faction_filter_0_rhs_faction_tv = true;
force zen_faction_filter_0_rhs_faction_vdv = true;
force zen_faction_filter_0_rhs_faction_vmf = true;
zen_faction_filter_0_rhs_faction_vmf_groups = true;
force zen_faction_filter_0_rhs_faction_vpvo = true;
force zen_faction_filter_0_rhs_faction_vv = true;
force zen_faction_filter_0_rhs_faction_vvs = true;
force zen_faction_filter_0_rhs_faction_vvs_c = true;
force zen_faction_filter_1_ = true;
force zen_faction_filter_1_BLU_CTRG_F = true;
force zen_faction_filter_1_BLU_F = true;
force zen_faction_filter_1_BLU_G_F = true;
force zen_faction_filter_1_BLU_GEN_F = true;
force zen_faction_filter_1_BLU_T_F = true;
force zen_faction_filter_1_BLU_W_F = true;
force zen_faction_filter_1_BWA3_Faction_Fleck = true;
force zen_faction_filter_1_BWA3_Faction_Multi = true;
force zen_faction_filter_1_BWA3_Faction_Tropen = true;
force zen_faction_filter_1_DSF_ANA = true;
force zen_faction_filter_1_DSF_ANA_groups = true;
force zen_faction_filter_1_DSF_CIA = true;
force zen_faction_filter_1_DSF_COP = true;
force zen_faction_filter_1_DSF_CORP = true;
force zen_faction_filter_1_DSF_HTS = true;
force zen_faction_filter_1_DSF_IDF = true;
force zen_faction_filter_1_DSF_UAF = true;
force zen_faction_filter_1_DSF_UKR = true;
force zen_faction_filter_1_Redd_Vehicles = true;
force zen_faction_filter_1_rhs_faction_socom = true;
force zen_faction_filter_1_rhs_faction_usaf = true;
force zen_faction_filter_1_rhs_faction_usarmy_d = true;
force zen_faction_filter_1_rhs_faction_usarmy_wd = true;
force zen_faction_filter_1_rhs_faction_usmc_d = true;
force zen_faction_filter_1_rhs_faction_usmc_wd = true;
force zen_faction_filter_1_rhs_faction_usn = true;
force zen_faction_filter_1_VSM_GP = true;
force zen_faction_filter_2_DSF_ABUS = true;
force zen_faction_filter_2_DSF_ABUS_groups = true;
force zen_faction_filter_2_DSF_AFMIL = true;
force zen_faction_filter_2_DSF_BOKO = true;
force zen_faction_filter_2_DSF_CART = true;
force zen_faction_filter_2_DSF_CAUC = true;
force zen_faction_filter_2_DSF_ISIS = true;
force zen_faction_filter_2_DSF_MIL = true;
force zen_faction_filter_2_DSF_USMILITIA = true;
force zen_faction_filter_2_IND_C_F = true;
force zen_faction_filter_2_IND_E_F = true;
force zen_faction_filter_2_IND_F = true;
force zen_faction_filter_2_IND_G_F = true;
force zen_faction_filter_2_IND_L_F = true;
force zen_faction_filter_3_CIV_F = true;
force zen_faction_filter_3_CIV_IDAP_F = true;
force zen_faction_filter_3_DSF_Civilians = true;
force zen_faction_filter_3_EdCat_Supplies = true;
force zen_faction_filter_3_IND_L_F = true;
